src/monitor/.terraform.lock.hcl, src/monitor/00_data.tf, src/monitor/01_core.tf, src/monitor/99_locals.tf, src/monitor/99_main.tf, src/monitor/99_variables.tf, src/monitor/api/monitor_mock_policy.xml, src/monitor/api/monitor_openapi.json.tpl, src/monitor/api_product/base_policy.tpl, src/monitor/api_product/monitor_base_policy.xml, src/monitor/env/itn-dev/backend.ini, src/monitor/env/itn-dev/backend.tfvars, src/monitor/env/itn-dev/terraform.tfvars, src/monitor/terraform.sh
=> feat: Mock monitor api on root path

src/cittadini/api/cittadini/v1/area_riservata_cittadino_openapi.yml
- update swagger with transaction details endpoint
---
=> feat: P4PU-47 update swagger with transaction details endpoint

src/cittadini/api/cittadini/v1/area_riservata_cittadino_openapi.yml
- Added new endpoint transaction receipt to swagger
---
=> feat: P4PU-247 added new endpoint transaction receipt to swagger

src/cittadini/02_cittadini.tf, src/cittadini/api/cittadini/v1/_openapi.yml
=> feat: P4PU-170 apim-expose

src/cittadini/api/cittadini/v1/_openapi.yml
- Added enum error for invalid amount and date
---
=> chore: P4PU-193 Added enum error for invalid amount and date

src/cittadini/01_core.tf, src/cittadini/99_locals.tf, src/cittadini/api_product/_base_policy.xml
=> fix: P4PU-343 Make frontend public

src/cittadini/api/cittadini/v1/_openapi.yml
-  updated swagger with new endpoint payment-notices
---
=> feat: P4PU-290 updated swagger with new endpoint payment-notices

src/cittadini/api/cittadini/v1/_openapi.yml
- Added new error status on swagger
---
=> fix: P4PU-289 updated swagger with new error status

.github/workflows/pr-title.yml, src/cittadini/01_core.tf, src/cittadini/api_product/_base_policy.xml
=> fix: [P4PU-386] Update cors policy 

src/cittadini/api/cittadini/v1/_openapi.yml
- Added security schema on swagger 
---
=> feat: [P4PU-351] added security schema on swagger

src/cittadini/api/cittadini/v1/_openapi.yml
List of Changes
Fixed naming in open api definition to be camel case
Motivation and Context
Issue was causing missalignment with front end specification
---
=> fix: [P4PU-330] fixed naming in camel case

src/cittadini/api/cittadini/v1/_openapi.yml
Added user info endpoint 
Protected user info endpoint
This endpoint is required for front end to show the information about authenticated user, info will be provided in json format
---
=> feat: [P4PU-374] added user info endpoint

src/cittadini/env/itn-dev/terraform.tfvars
=> fix: Update dev cittadini domain

src/cittadini/api/cittadini/v1/_openapi.yml
=> feat: [P4PU-401] added user logout endpoint

src/cittadini/api/cittadini/v1/_openapi.yml
=> feat: [P4PU-512] added notices endpoint

src/cittadini/api/cittadini/v1/_openapi.yml
Added error code into api response 403
---
=> chore: [P4PU-562] added error code into api response

src/cittadini/api/cittadini/v1/_openapi.yml
- added notice details endpoint
---
=> feat: [P4PU-537] added notice details endpoint

src/cittadini/api/cittadini/v1/_openapi.yml
=> feat: [P4PU-547] update swagger with receipt endpoint

src/cittadini/03_apim_diagnostics.tf, src/cittadini/99_locals.tf, src/cittadini/99_variables.tf, src/cittadini/env/itn-dev/terraform.tfvars, src/cittadini/env/itn-uat/terraform.tfvars
=> chore: [P4PU-622] added apim diagnostic

src/cittadini/api/cittadini/v1/_openapi.yml
removed api details from apim
---
=> feat: [P4PU-539] removed api details from apim

src/cittadini/api/cittadini/v1/_openapi.yml
removed api transcation receipt from apim
---
=> feat: [P4PU-540] removed api transcation receipt from apim

src/cittadini/01_apim_core.tf, src/cittadini/api_product/_base_policy.xml
=> fix: cors@UAT

CODEOWNERS, src/cittadini/api/cittadini/v1/_openapi.yml
- added totalAmount on notice details
---
=> feat: [P4PU-741] added totalAmount on notice details

src/cittadini/api/cittadini/v1/_openapi.yml
-added payment notices details endpoint
---
=> feat: [P4PU-757] added payment notices details endpoint

src/cittadini/api/cittadini/v1/_openapi.yml
- Updated swagger with new response of payment-notices API
---
=> fix: [P4PU-798] Updated swagger with new response of payment-notices API

src/cittadini/04_health.tf, src/cittadini/api/cittadini/health/health_base_policy.xml, src/cittadini/api/cittadini/health/health_openapi.yml, src/cittadini/api/cittadini/v1/_openapi.yml
=> feat: [P4PU-817] added /actuator/health/liveness endpoint

src/cittadini/api/cittadini/v1/_openapi.yml
- added header to receipt response on swagger
---
=> fix: [P4PU-826] added header to receipt response on swagger
